.TH man 8 "18 Oct, 2017" "ovirt-engine-hyper-upgrade man page"
.SH NAME
ovirt-engine-hyper-upgrade \- A tool to help users upgrade RHV Manager
.SH SYNOPSIS
ovirt-engine-hyper-upgrade.py [-h] [--backup-dir BACKUP_DIR]
                                  [--upgrade-to-rhv UPGRADE_TO_RHV]

.SH DESCRIPTION
\fBovirt-engine-hyper-upgrade\fP is a command line tool to manage upgrades for RHV Manager.
.P

.TP
.B --backup-dir
Directory where the engine-backup will save the backup file.
If not provided, it will use /tmp

.TP
.B --upgrade-to-rhv
Upgrade to specifc version of RHV

.SH LOGGING
See \fB/var/log/ovirt-engine/engine-hyper-upgrade.log
.SH BUGS
Report bugs to <http://bugzilla.redhat.com>

.SH COPYRIGHT
Copyright 2017 Red Hat, Inc.
