.TH man 8 "18 Oct, 2017" "ovirt-engine-hyper-upgrade man page"
.SH NAME
ovirt-engine-hyper-upgrade \- A tool to help users upgrade RHV environments
.SH SYNOPSIS
ovirt-engine-hyper-upgrade.py [-h] [--check-upgrade-rhv-4-0]
                                   [--check-upgrade-rhv-4-1]
.SH DESCRIPTION
\fBovirt-engine-hyper-upgrade\fP is a command line tool to manage upgrades for RHV.
.P

.TP
.B --check-upgrade-rhv-4-0
Check if there are upgrades for RHV 4.0 zstream and enable 4.1 repositories

.TP
.B --check-upgrade-rhv-4-1
Check if there are upgrades for RHV 4.0 zstream and enable 4.2 repositories

.SH LOGGING
See \fB/var/log/engine-hyper-upgrade.log
.SH BUGS
Report bugs to <http://bugzilla.redhat.com>

.SH COPYRIGHT
Copyright 2017 Red Hat, Inc.
