#!/usr/bin/python
#
#  Licensed under the Apache License, Version 2.0 (the "License");
#  you may not use this file except in compliance with the License.
#  You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
#  Unless required by applicable law or agreed to in writing, software
#  distributed under the License is distributed on an "AS IS" BASIS,
#  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#  See the License for the specific language governing permissions and
#  limitations under the License.
#
import argparse
import json
import logging
import os
import rpm
import signal
import subprocess
import sys
import tempfile

from datetime import datetime
from enum import Enum


LOGGING_FILE = "/var/log/ovirt-engine/ovirt-fast-forward-upgrade.log"

RHV_40_REPOS = [
    "rhel-7-server-supplementary-rpms",
    "rhel-7-server-rpms",
    "rhel-7-server-rhv-4.0-rpms",
    "jb-eap-7.0-for-rhel-7-server-rpms"
]

RHV_41_REPOS = [
    "rhel-7-server-supplementary-rpms",
    "rhel-7-server-rpms",
    "rhel-7-server-rhv-4.1-rpms",
    "rhel-7-server-rhv-4-tools-rpms",
    "jb-eap-7.1-for-rhel-7-server-rpms"
]

RHV_42_REPOS = [
    "rhel-7-server-supplementary-rpms",
    "rhel-7-server-rpms",
    "rhel-7-server-rhv-4.2-manager-rpms",
    "rhel-7-server-rhv-4-manager-tools-rpms",
    "rhel-7-server-ansible-2-rpms",
    "jb-eap-7-for-rhel-7-server-rpms"
]

RHV_43_REPOS = [
    "rhel-7-server-supplementary-rpms",
    "rhel-7-server-rpms",
    "rhel-7-server-rhv-4-beta-rpms",
    "rhel-7-server-rhv-4-tools-beta-rpms",
    "rhel-7-server-ansible-2-rpms",
    "jb-eap-7.2-for-rhel-7-server-rpms"
]

# Dictionary that keep the release data like:
# version, the difference between repo_to_enable and repo_to_disable
CHECK_RELEASES = {}
CHECK_RELEASES['repos'] = [
    {
        'version': '4.0',
        'repo_to_enable': set(RHV_41_REPOS) - set(RHV_40_REPOS),
        'repo_to_disable': set(RHV_40_REPOS) - set(RHV_41_REPOS)
    },
    {
        'version': '4.1',
        'repo_to_enable': set(RHV_42_REPOS) - set(RHV_41_REPOS),
        'repo_to_disable': set(RHV_41_REPOS) - set(RHV_42_REPOS)
    },
    {
        'version': '4.2',
        'repo_to_enable': set(RHV_43_REPOS) - set(RHV_42_REPOS),
        'repo_to_disable': set(RHV_42_REPOS) - set(RHV_43_REPOS)
    }
]


class MsgType(Enum):
    INFO = 1
    WARNING = 2
    ERROR = 3


def _configure_logging():
    """
    The logging settings
    """
    logger = logging.getLogger(__name__)
    logger.setLevel(logging.DEBUG)
    logger.propagate = False

    fh = logging.FileHandler(LOGGING_FILE)
    fh.setLevel(logging.DEBUG)
    debug_fmt = logging.Formatter("%(asctime)s %(message)s",
                                  "%m/%d/%Y %I:%M:%S %p")

    ih = logging.StreamHandler(stream=sys.stdout)
    ih.setLevel(logging.INFO)
    info_fmt = logging.Formatter("%(message)s",
                                 "%m/%d/%Y %I:%M:%S %p")

    fh.setFormatter(debug_fmt)
    ih.setFormatter(info_fmt)

    logger.addHandler(fh)
    logger.addHandler(ih)

    logging.captureWarnings(True)


class Base(logging.Handler):
    def __init__(self):
        super(Base, self).__init__()
        self.logger = logging.getLogger(__name__)

    def print_msg(self, message, type=None):
        """
        Print message

        Parameters:
           type
               INFO - The message will be print as green
               WARNING - The message will be print as yellow

        Argument:
            message - Message to be printed with INFO note
        """

        if type == MsgType.ERROR:
            self.logger.error((
                "\033[91m[ ERROR  ]\033[00m {msg}".format(msg=message)
            ))
        elif type == MsgType.INFO:
            self.logger.info((
                "\033[92m[ INFO  ]\033[00m {msg}".format(msg=message)
            ))
        elif type == MsgType.WARNING:
            self.logger.info((
                "\033[93m[ WARNING  ]\033[00m {msg}".format(msg=message)
            ))
        else:
            self.logger.info((
                "{m}".format(m=message)
            ))

    def execute_cmd_remote_host_check_output(self, host, command):
        """
        Execute Command in a remote host and check output
        """

        key = "/etc/pki/ovirt-engine/keys/engine_id_rsa"
        if not os.path.exists(key):
            raise RuntimeError("Can't find engine private key!")

        cmd = (
            "ssh -i {key} {host} {command}".format(
                key=key, host=host, command=command)
        )
        return self.execute_cmd_check_output(cmd)

    def execute_cmd_check_output(self, command, shell=True):
        """
        Execute command returning output

        Parameters:
            command - command to be executed
            shell - True or False
                    If shell is True, the specified command will be
                    executed through the shell

        Returns: output from command or exit
        """
        # We don't need to print the SQL queries
        if not "engine-db-query" in command:
            self.print_msg(
                'Executing: {cmd}'.format(cmd=command),
                MsgType.INFO
            )

        try:
            output = subprocess.check_output(command, shell=shell)
        except subprocess.CalledProcessError as e:
            self.print_msg(
                e.output,
                MsgType.ERROR
            )
            sys.exit(2)

        self.logger.debug(output)

        return output

    def execute_cmd(self, command, shell=False):
        """
        Execute command

        Parameters:
            command - command to be executed, use ['cmd' 'argument']
            shell - True or False
                    If shell is True, the specified command will be
                    executed through the shell

        Returns: return code or exit in case of failure
        """

        cmd_str = ' '.join(command)
        self.print_msg(
            'Executing: {cmd}'.format(cmd=cmd_str),
            MsgType.INFO
        )

        p = subprocess.Popen(
            command,
            shell=shell
        )
        returncode = p.wait()

        if returncode != 0:
            self.logger.debug(
                'ATTENTION: {cmd}, return code: {ret}'.format(
                    cmd=cmd_str, ret=returncode)
            )

        return returncode


class Subscriptions(Base):
    def __init__(self):
        super(Subscriptions, self).__init__()
        self.repos = []

    def get_enabled_repos(self):
        '''
        Get enabled repos

        Returns: All enabled repos id or empty list
        '''
        self.repos = []

        rhsm_cmd = [
            'env',
            'LC_ALL=C',
            'subscription-manager',
            'repos',
            '--list-enabled'
        ]

        # Convert to str to be used with check_output and shell=True
        rhsm_cmd = ' '.join(rhsm_cmd)

        self.print_msg(
            'Collecting enabled repositories by subscription-manager...',
            MsgType.INFO
        )

        output_rhsm = self.execute_cmd_check_output(rhsm_cmd)

        # We need to parse output of subscription-manager, using check_output
        for line in output_rhsm.splitlines():
            if('Repo ID:' in line):
                value = line.split('Repo ID:')[1]
                self.repos.append(value.strip())

        return self.repos

    def check_rhv_repos(self, version):
        '''
        Check repositories for RHV

        Parameters:
            version: RHV version to check, example of values (str):
                4.0
                4.1
                4.2

        Returns: True or False
        '''
        self.get_enabled_repos()
        enabled = set(self.repos)

        if version == '4.0':
            required = set(RHV_40_REPOS)
        elif version == '4.1':
            required = set(RHV_41_REPOS)
        elif version == '4.2':
            continue_upgrade = raw_input(
                'Upgrading to RHV 4.3... cluster compatibility version '
                '3.6 and 4.0 are not supported. Are you sure you want to '
                'continue? [N/y]'
            ).lower().strip()
            if not continue_upgrade or continue_upgrade[0] != "y":
                logger.info('Aborting...')
                sys.exit(0)
            required = set(RHV_42_REPOS)
        else:
            raise RuntimeError('Version parameters not supported!')

        unknown = enabled.difference(required)
        missing = required.difference(enabled)

        if missing:
            self.print_msg("The following repositories are required "
                           "for {ver}".format(ver=version), MsgType.WARNING)
            for repo in missing:
                self.print_msg(" - {repo}".format(repo=repo))

        if unknown:
            self.print_msg(
                "The following repositories are enabled and not the "
                "main repositories for RHV {ver}".format(ver=version),
                MsgType.WARNING)
            for repo in unknown:
                self.print_msg(" - {repo}".format(repo=repo))

        if missing or unknown:
            return False

        return True

    def repository(self, action, repos):
        '''
        Enable repository using subscription-manager
        Parameters:
            action
                enable  - Enable channel
                disable - Disable channel

            repos
                repos name (list)
        Returns: command output
        '''

        SUBSCRIPTION_MANAGER_CMD = [
            'env',
            'LC_ALL=C',
            'subscription-manager',
            'repos'
        ]

        if 'enable' == action:
            rhsm_enable_cmd = list(SUBSCRIPTION_MANAGER_CMD)
            for repo in repos:
                self.print_msg(
                    'Enabling repository: {r}'.format(r=repo),
                    MsgType.INFO
                )
                rhsm_enable_cmd.extend(['--enable', repo])

            if self.execute_cmd(rhsm_enable_cmd) != 0:
                self.print_msg(
                    'Cannot enable repository: {r}'.format(r=repo),
                    MsgType.ERROR
                )
                sys.exit(2)

        elif 'disable' == action:
            rhsm_disable_cmd = list(SUBSCRIPTION_MANAGER_CMD)
            for repo in repos:
                self.print_msg(
                    'Disabling repository: {r}'.format(r=repo),
                    MsgType.INFO
                )
                rhsm_disable_cmd.extend(['--disable', repo])

            if self.execute_cmd(rhsm_disable_cmd) != 0:
                self.print_msg(
                    'Cannot disable repository: {r}'.format(r=repo),
                    MsgType.ERROR
                )
                sys.exit(2)
        else:
            raise RuntimeError(
                "Unknown action [%s] for repositories!" % action
            )


class UpgradeHelper(Base):

    UPGRADE_CHECK = [
        'env',
        'LC_ALL=C',
        'engine-upgrade-check'
    ]

    YUM_UPDATE_CMD = [
        'env',
        'LC_ALL=C',
        'yum', 'update'
    ]

    ENGINE_SETUP = [
        'env',
        'LC_ALL=C',
        'engine-setup'
    ]

    HE_SET_MAINTENANCE_NONE = (
        "env "
        "LC_ALL=C "
        "hosted-engine "
        "--set-maintenance "
        "--mode=none"
    )

    HE_SET_MAINTENANCE_GLOBAL = (
        "env "
        "LC_ALL=C "
        "hosted-engine "
        "--set-maintenance "
        "--mode=global"
    )

    def __init__(self):
        super(UpgradeHelper, self).__init__()
        self.hosted_engine = None
        self.hosted_engine_host = None

    def is_upgrade_available(self):
        '''
        Execute engine-upgrade-check
        Returns: command return code, engine-upgrade-check returns 1 in case
        there is no upgrade. It's not like yum command that returns 1 only
        in case of error. So we return the returncode to the caller to be able
        to decide if there is upgrade or not to take the next action.
        '''
        return self.execute_cmd(self.UPGRADE_CHECK)

    def upgrade_engine_setup(self):
        '''
        Look for packages with ovirt-engine-setup* name
        and execute yum update. In case of failure, exit.
        '''

        yum_update_engine_cmd = list(self.YUM_UPDATE_CMD)
        yum_update_engine_cmd.extend([
            'ovirt-engine-*setup*',
        ])

        if self.execute_cmd(yum_update_engine_cmd) != 0:
            self.print_msg(
                'Aborting.. yum update ovirt-engine-*setup* failed...',
                MsgType.ERROR
            )
            sys.exit(2)

    def check_he_running(self):
        '''
        Check if the environment is Hosted Engine
        '''
        SQL_QUERY = (
            "SELECT                           "
            "    vm_name,                     "
            "    host_name                    "
            "FROM                             "
            "    vms, vds                     "
            "WHERE                            "
            "    vms.run_on_vds=vds.vds_id AND"
            "    vms.origin = 6               "
        )
        ret = self.execute_cmd_check_output(
                'engine-db-query --json -s "{cmd}"'.format(cmd=SQL_QUERY)
        )

        if ret:
            data = json.loads(ret)
            for result in data['result']:
                for ret in result:
                    self.hosted_engine = ret['vm_name']
                    self.hosted_engine_host = ret['host_name']

    def he_set_maintenance_global(self):
        '''
        Hosted Engine - Set Maintenance Global
        '''
        self.check_he_running()
        if self.hosted_engine is not None:
            self.print_msg(
                'Hosted Engine - Setting Maintenance Global',
                MsgType.INFO
            )
            self.execute_cmd_remote_host_check_output(
                self.hosted_engine_host,
                self.HE_SET_MAINTENANCE_GLOBAL
            )

    def he_set_maintenance_none(self):
        '''
        Hosted Engine - Set Maintenance None
        '''
        self.check_he_running()
        if self.hosted_engine is not None:
            self.print_msg(
                'Hosted Engine - Setting Maintenance None',
                MsgType.INFO
            )
            self.execute_cmd_remote_host_check_output(
                self.hosted_engine_host,
                self.HE_SET_MAINTENANCE_NONE
            )

    def run_engine_setup(self):
        '''
        Execute engine-setup or exit in case of failure
        '''

        # Check if HE is running and set maint global
        self.he_set_maintenance_global()

        if self.execute_cmd(self.ENGINE_SETUP) != 0:
            self.print_msg(
                'Aborting.. engine-setup failed...',
                MsgType.ERROR
            )
            self.he_set_maintenance_none()
            sys.exit(2)

        self.he_set_maintenance_none()

    def update_system(self):
        '''
        Execute yum update or exit in case of failure
        '''
        if self.execute_cmd(self.YUM_UPDATE_CMD) != 0:
            self.print_msg(
                'Aborting.. yum update failed...',
                MsgType.ERROR
            )
            sys.exit(2)

    def detect_major_version_engine(self):
        '''
        Detect major version of oVirt Engine
        '''
        engine_package = 'ovirt-engine'
        major_version_engine = None

        ts = rpm.TransactionSet()
        mi = ts.dbMatch()

        for package in mi:
            if package['name'] == engine_package:
                # Get the major version
                major_version_engine = package['version'][:3]

                self.logger.debug(
                    'Major version {pkg}: {majorv}'.format(
                        pkg=engine_package, majorv=major_version_engine)
                )

        if major_version_engine is None:
            self.print_msg(
                'Aborting.. unable to find {pkg} package to detect major '
                'version...'.format(pkg=engine_package),
                MsgType.ERROR
            )
            sys.exit(2)

        return major_version_engine

    def run_engine_backup(self, dir_to_save_backup):
        '''
        Execute engine-backup before upgrade

        Arguments:
        dir_to_save_backup
            Directory to engine-backup tool save the bkp file
        '''
        engine_backup_file = '{dirbkp}/backup-engine-{date_time}'.format(
            dirbkp=dir_to_save_backup,
            date_time=datetime.now().strftime('%Y-%m-%d_%H-%M-%S')
        )

        ENGINE_BACKUP_CMD = [
            'env',
            'LC_ALL=C',
            'engine-backup',
            '--scope=all',
            '--mode=backup',
            '--file=' + engine_backup_file + '.bck',
            '--log=' + engine_backup_file + '.log'
        ]

        if self.execute_cmd(ENGINE_BACKUP_CMD) != 0:
            self.print_msg(
                'Aborting.. engine-backup failed...',
                MsgType.ERROR
            )
            sys.exit(2)


def main():
    '''
    A tool to help users upgrade RHV environments
    '''
    logger = logging.getLogger(__name__)

    parser = argparse.ArgumentParser(
        formatter_class=argparse.RawTextHelpFormatter,
        description='Tool to upgrade RHV environments',
        epilog='Example of use:\n%(prog)s '
    )

    parser.add_argument(
        '--backup',
        action='store_true',
        help='Execute engine-backup before upgrade',
    )

    parser.add_argument(
        '--backup-dir',
        nargs=1,
        help='Directory where the engine-backup will save the output\n'
             'If not provided, it will use /tmp',
    )

    logger.debug('----------------------')
    logger.debug('Starting')
    logger.debug('----------------------')

    args = parser.parse_args()

    if args.backup_dir and not args.backup:
        logger.error('The option --backup-dir requires --backup!')
        sys.exit(2)

    c = Subscriptions()

    if args.backup:
        if args.backup_dir is None:
            bkp_dir = tempfile.gettempdir()
        else:
            bkp_dir = ' '.join(args.backup_dir)

    upgrade_supported = False

    u = UpgradeHelper()
    for release in CHECK_RELEASES['repos']:
        version = u.detect_major_version_engine()

        if release['version'] == version:
            upgrade_supported = True
            if c.check_rhv_repos(release['version']) is False:
                continue_upgrade = raw_input(
                    'Are you sure you want to continue? It might generate '
                    'conflicts on RPM dependency. [N/y]'
                ).lower().strip()
                if not continue_upgrade or continue_upgrade[0] != "y":
                    logger.info('Aborting...')
                    sys.exit(0)

            if args.backup:
                u.run_engine_backup(bkp_dir)

            # If there is no update, engine-upgrade-check return 1
            if u.is_upgrade_available() != 1:
                logger.info("An upgrade is available, upgrading to "
                            "latest {version}.z".format(
                                version=release['version']))

                u.upgrade_engine_setup()
                u.run_engine_setup()

            u.update_system()

            c.repository(action='enable', repos=release['repo_to_enable'])
            u.upgrade_engine_setup()
            u.run_engine_setup()

            u.update_system()

            c.repository(action='disable', repos=release['repo_to_disable'])

    if upgrade_supported is False:
        logger.error(
            'Unable to upgrade this environment to {v} version!'.format(
                v=version)
        )
        sys.exit(2)

    logger.info("Please reboot the system to complete the update.")
    logger.info(
        "Once rebooted, please change the cluster and datacenter "
        "compatibility level to the latest version.\n"
    )

    return 0


if __name__ == '__main__':

    signal.signal(signal.SIGINT, signal.SIG_IGN)
    signal.signal(signal.SIGTSTP, signal.SIG_IGN)

    if os.geteuid() != 0:
        sys.exit("User root is required for this program manage "
                 "the subscriptions in this system!")

    _configure_logging()
    sys.exit(main())

# vim: expandtab tabstop=4 shiftwidth=4
